import TestButton from '@components/TestButton'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null)
  const [products, setProducts] = useState<
    { id: string; properties: { id: string }[] }[]
  >([])

  useEffect(() => {
    fetch('/api/get-items')
      .then((res) => res.json())
      .then((data) => setProducts(data.items))
  }, [])

  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === '') {
      return alert('name을 넣어주세요.')
    }

    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TestButton />
        <input ref={inputRef} type="text" placeholder="name" />
        <button onClick={handleClick}>Add Jacket Test Button</button>
        <div>
          <p>Product List</p>
          {products &&
            products.map((item) => (
              <div key={item.id}>
                {JSON.stringify(item)}
                {item.properties &&
                  Object.entries(item.properties).map(([key, value]) => (
                    <button
                      key={key}
                      onClick={() => {
                        fetch(
                          `api/get-detail?pageId=${item.id}&propertyId=${value.id}`,
                        )
                          .then((res) => res.json())
                          .then((data) => alert(JSON.stringify(data.detail)))
                      }}
                    >
                      {key}
                    </button>
                  ))}
                <br />
                <br />
              </div>
            ))}
        </div>
      </main>
    </>
  )
}
